package pe.aioo.openmoa.view.message

enum class SpecialKey {
    ARROW,
    ARROW_UP,
    ARROW_LEFT,
    ARROW_RIGHT,
    ARROW_DOWN,
    BACKSPACE,
    COPY,
    COPY_ALL,
    CUT,
    CUT_ALL,
    DELETE,
    EMOJI,
    END,
    ENTER,
    HANJA_NUMBER_PUNCTUATION,
    HOME,
    LANGUAGE,
    PASTE,
    SELECT_ALL,
    SELECT_ARROW_UP,
    SELECT_ARROW_LEFT,
    SELECT_ARROW_RIGHT,
    SELECT_ARROW_DOWN,
    SELECT_END,
    SELECT_HOME,
}